package constant

const(
	ServerKey = "AAAA_UfK7aw:APA91bHPeevBAtEDrtPb0B-XlWgUbmWGFgVnI1GqpQiJo3IdSV90HbxxYze2surz1f9cn9K_Pzvx2Ry5FOqM3CUsptGFzinsOHk0YU-nne9QiqtqYxnjr9WCuYOmuyBIQKfRHKaKuNDwwkXOwoJHtoF1y4dw9kW_RQ"

)
